name: Push firmware update

on:
  workflow_dispatch:

jobs:
  push-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Generate firmware.json
        run: |
          echo '{
            "version": "1.2.3",
            "date": "'$(date +%Y-%m-%d)'",
            "url": "https://github.com/kelvin/homio-updates/releases/download/v1.2.3/firmware-v1.2.3.bin",
            "checksum": "abc123def456..."
          }' > firmware.json

      - name: Push to homio-updates
        run: |
          git config --global user.name "homio-bot"
          git config --global user.email "homiobot3@gmail.com"
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/kelvin/homio-updates.git
          cp firmware.json homio-updates/
          cd homio-updates
          git add firmware.json
          git commit -m "Update firmware metadata v1.2.3"
          git push